### ISSUE TITLE
Why the old image was removed?

### ISSUE THREAD

**Issue by fwynyk** [roffe/kube-gelf#1]
https://hub.docker.com/r/roffe/kube-gelf/tags/

I was using your image and now someway the new one is broken. And the old image was removed. Can you bring the old image as a "1" version?

**Comment by roffe** [comment]
Old image was removed as I corrected a mistake where I had used a old version of out_gelf.rb from https://raw.githubusercontent.com/bedag/fluent-plugin-gelf/master/lib/fluent/plugin/out_gelf.rb

And replaced it with 

https://raw.githubusercontent.com/emsearcy/fluent-plugin-gelf/master/lib/fluent/plugin/out_gelf.rb

I did test this version in multiple clusters before pushing the new image, Could you please try to give me some more details on what went wrong?

As requested I made a v1.0 image with the old output filter. It's being built as we speak.

Cheers and thanks for the feedback!

**Comment by roffe** [comment]
To ensure this won't happen again I will make sure to branch properly in the future. 

Sorry for any inconvenience

**Comment by roffe** [comment]
It seems there are issues with the new vendored version so i have reverted `latest` as well to the old version.
