### ISSUE TITLE
Helm Chart

### ISSUE THREAD

**Issue by mhobotpplnet** [roffe/kube-gelf#16]
I created helm chart for this project, let me know if you want me to share it. Its pretty easy to install it.

**Comment by roffe** [comment]
Please do, i have not been using helm charts but i know a lot of people appreciate them

**Comment by mhobotpplnet** [comment]
Sounds good, ill shoot it over to you as PR, I just need to make some variables and cleanup my personal stuff. Its much easier to install it like 
helm install graylog
helm install kubegelf 
Done..

**Comment by roffe** [comment]
Awesome, Thank you @mhobotpplnet
