### ISSUE TITLE
When graylog gets restarted kube-gelf can't reach it

### ISSUE THREAD

**Issue by mhobotpplnet** [roffe/kube-gelf#3]
Thanks for the kube-gelf , however I must say that when graylog pod is restarted and gets new IP , the configmap needs to be updated. The only way to really get it to work is to turn off hostNetwork, however that only than gives you kube-gelf pod logs.

Is there a way instead of using a IP address to use graylog host name of some sort?

**Comment by roffe** [comment]
Hi @mhobotpplnet!

You can enter any valid hostname/FQDN/ip in the key GELF_HOST

Updated the readme to be clearer about this with commit. https://github.com/roffe/kube-gelf/commit/a163de8ea23ca521f103074a0bb0ded16e303b77

If you are running graylog as a deployment i suggest creating a service that targets the log collector port, then in your kube-gelf configmap point GELF_HOST to (for example) `graylog-collector.graylog.svc.cluster.local` ( Kubernetes DNS names will vary depending on deploy )

**Comment by mhobotpplnet** [comment]
See the issue I have is.
When I comment out hostNetwork I get Nodes nameservers '*....svc.cluster.local etc' ,therefore I was able to ping and reach a pod in my namespace from kube-gelf* kube-system namespace, however looking at the logs shipped, it only provides me kube-gelf logs and not K8 all logs. 

If I leave hostNetwork=true, and specify IP of GL pod than I get all pods logs, issue becomes when graylog server is restarted for whatever reason it gets new IP address. 

One way I can see this fixing is by forcing nameservers into kube-gelf pod so it can resolve graylog-collector.graylog.svc.cluster.local.

Here is example of what I tried with and without hostnetwork, as you can see below: I can ping google no problem , thats because it has generic nameservers but not from node. 

`kube-shell> kubectl exec -ti kube-gelf-11111 ping graylog-collector.graylog.svc.cluster.local --namespace k
ube-system
ping: graylog-collector.graylog.svc.cluster.local: Name or service not known
command terminated with exit code 2

kube-shell> kubectl exec -ti kube-gelf-11111 ping google.com --namespace kube-system
PING google.com (172.217.3.206) 56(84) bytes of data.
64 bytes from sea15s12-in-f14.1e100.net (172.217.3.206): icmp_seq=1 ttl=45 time=23.5 ms
64 bytes from sea15s12-in-f14.1e100.net (172.217.3.206): icmp_seq=2 ttl=45 time=23.0 ms
64 bytes from sea15s12-in-f14.1e100.net (172.217.3.206): icmp_seq=3 ttl=45 time=23.1 ms`

**Comment by roffe** [comment]
Ahh yes i see.

One way around this would be to set the dnsPolicy to "ClusterFirstWithHostNet" when running in hostnetwork

on the line after `hostNetwork: true` add `dnsPolicy: ClusterFirstWithHostNet` on the same indentation and try again.

https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pods-dns-policy

**Comment by roffe** [comment]
I will consider adding "dnsPolicy: ClusterFirstWithHostNet" in the deployment. ideally i would like to get the node hostname in the gelf config witout running in in hostNetwork as it shouldn't be required.

**Comment by mhobotpplnet** [comment]
Well there are few ways of fixing this.
1. static IP for pod? :) not really ideal but works
2. add nameserver of Node to kube-gelf pod(s)
3. use dnsPolicy cluster first.

I wonder how say sumologic does this w/o any issue? 
https://github.com/SumoLogic/fluentd-kubernetes-sumologic

**Comment by roffe** [comment]
1. Not a good idea as you say, we want to avoid this. use a service with selector targeting the pod and use DNS discovery to avoid locking us into IP's

2. When not specifying any dnsPolicy and using hostNetwork afaik, this is what it does. 
we want the cluster DNS to resolve k8sinternal dns names for services.

3. this is default unless specifying other or running with hostNetwork.
"If dnsPolicy is not explicitly specified, then “ClusterFirst” is used."

If you can live with that kube-gelf is reporting the pod names as log source instead of the nodename where it's ran you should be able to remove hostNetwork true and specify the dnsPolicy to cluster first and after that you should be able to use the DNS discovery names provided by services in K8S

**Comment by roffe** [comment]
The one and only reason i use hostNetwork true is so the kube-gelf pod on each node gets the nodes HOSTNAME instead of the pods name to make it clear where the logs is coming from.

**Comment by mhobotpplnet** [comment]
I created the extraction fields for pods and namespace

Namespace: 
e":"(.*?)"

PodName:
pod_name":"(.*?)"

So you can then select or do query by podname

**Comment by roffe** [comment]
yes, i'm however talking about the source filed that will appear in graylog

**Comment by roffe** [comment]
It's a goal for me to get rid of it but due to much work i havn't had time to prioritize it

**Comment by mhobotpplnet** [comment]
Np :) great work tho. 
I would like to expand more on fluentd.conf file so that msgs log more pretty. 
Thanks for help, with hostname = true and dnspolicy .. issue has been resolved.. Not ideal or best practice.. but it works for now :)

**Comment by roffe** [comment]
I've created a issue to fix this and get rid of hostNetwork. probably i will use the downward API to get the nodehostname and place it in a special ENV variable i will use.

Hopefully i can get this done by tonight :)

**Comment by roffe** [comment]
@mhobotpplnet sorry for the late update. I've updated the project with the latest fluentd + plugins & did the change to get rid of hostNetwork.

It requires a small configmap change when you update. Please see the README.md and patch your existing one according to the new updated fluent.conf in my repo.

You will get a new field in graylog with the nodename from the downward api to be able to identify which machine the logs originate from.

**Comment by roffe** [comment]
Scratch the part about changing your config. i realized that the  fluent-plugin-graylog output module dos not support UDP so we are keeping the old one for now

**Comment by mhobotpplnet** [comment]
Sounds good. 
Well I got the whole set going for now, how does your fluentd conf look like?
By the way, would it help if I gave you helm chart? I turned your gelf into helm chart.

**Comment by roffe** [comment]
fluent.conf is included in the root of the repo

I would be interested in the helm chart.

Maybe we could take this to the next level if people find good use of this project :)

**Comment by mhobotpplnet** [comment]
I'll be glad to help. Its awesome project. And pretty much only one that 'works'
