### ISSUE TITLE
Add project to Graylog Marketplace

### ISSUE THREAD

**Issue by joschi** [roffe/kube-gelf#9]
Thanks for creating and maintaining this interesting project! 😃 

It would be great if you could add kube-gelf to the [Graylog Marketplace](https://marketplace.graylog.org/), so that other Kubernetes and Graylog users can easily discover it.

Instructions for adding projects to the Graylog Marketplace can be found at http://docs.graylog.org/en/2.4/pages/marketplace.html

**Comment by roffe** [comment]
Thanks for the feedback @joschi I will look into this! :)

**Comment by roffe** [comment]
Done :)
https://marketplace.graylog.org/addons/2d12db17-a4cf-4e4b-87cd-347b084bfbcb

**Comment by joschi** [comment]
@roffe Great, thanks!
